apiVersion: v1
kind: ConfigMap
metadata:
  name: tracardi-gui-config
data:
  custom.js: |
    export const custom = {}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tracardi-api.fullname" . }}-gui-deployment
  labels:
    app: {{ include "tracardi-api.fullname" . }}-gui
    tier: frontend
spec:
  replicas: {{ .Values.tracardi.replicas.gui }}
  selector:
    matchLabels:
      app: {{ include "tracardi-api.fullname" . }}-gui
  template:
    metadata:
      labels:
        app: {{ include "tracardi-api.fullname" . }}-gui
        tier: frontend
    spec:
      containers:
        - name: {{ include "tracardi-api.fullname" . }}-gui
          image: {{ .Values.tracardi.image.gui }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: gui-port
          volumeMounts:
            - name: gui-config-volume
              mountPath: /usr/share/nginx/html/config
      volumes:
        - name: gui-config-volume
          configMap:
            # Provide the name of the ConfigMap containing the files you want to add to the container
            name: tracardi-gui-config

---
apiVersion: v1
kind: Service
metadata:
  name: tracardi-gui-svc
spec:
  type: ClusterIP
  selector:
    app: {{ include "tracardi-api.fullname" . }}-gui
  ports:
    - protocol: TCP
      port: {{ .Values.tracardi.port.gui }}
      targetPort: gui-port

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: {{ include "tracardi-api.fullname" . }}-gui-lb
#{{ if eq .Values.tracardi.doSSL "yes" }}
#  annotations:
#    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
#    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
#    service.beta.kubernetes.io/do-loadbalancer-certificate-id: {{ .Values.tracardi.elastic.doCertId | quote }}
#{{end}}
#spec:
#  type: LoadBalancer
#  selector:
#    app: {{ include "tracardi-api.fullname" . }}-gui
#  ports:
#    - name: http
#      protocol: TCP
#      port: {{ .Values.tracardi.port.gui }}
#      targetPort: gui-port
#{{ if eq .Values.tracardi.doSSL "yes" }}
#    - name: https
#      protocol: TCP
#      port: 443
#      targetPort: gui-port
#{{end}}
