apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-standalone-deployment
  labels:
    app: elastic-standalone
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-standalone
  template:
    metadata:
      labels:
        app: elastic-standalone
        tier: backend
    spec:
      containers:
        - name: elastic-standalone
          image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: elastic-9300
              containerPort: 9300
            - name: elastic-9200
              containerPort: 9200
          resources:
            limits:
              memory: 1Gi
              cpu: 1000m
            requests:
              memory: 512Mi
              cpu: 400m
          env:
            - name: discovery.type
              value: "single-node"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"

---
apiVersion: v1
kind: Service
metadata:
  name: elastic-std-svc
spec:
  type: ClusterIP
  selector:
    app: elastic-standalone
  ports:
    - name: elastic-9300
      protocol: TCP
      port: 9300
      targetPort: elastic-9300
    - name: elastic-9200
      protocol: TCP
      port: 9200
      targetPort: elastic-9200