{{ if and .Values.secrets.dockerHub .Values.worker.storage.profile.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wk-pl-storage-profile
  labels:
    {{- include "tracardi.labels" (dict "ctx" . "component" "wk-pl-storage-profile") | nindent 4 }}
spec:
  replicas: {{ .Values.worker.storage.session.replicas }}
  selector:
    matchLabels:
      {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "wk-pl-storage-profile") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tracardi.podLabels" (dict "ctx" . "component" "wk-pl-storage-profile") | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.secrets.dockerHub | quote }}
      containers:
        - name: wk-pl-storage-profile
          image: "{{ .Values.worker.storage.image.repository }}:{{ .Values.worker.storage.image.tag }}"
          imagePullPolicy: {{ .Values.worker.storage.image.pullPolicy }}
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
            requests:
              memory: 50Mi
              cpu: 50m
          env:
            {{- include "tracardi.env" (dict "ctx" .) | nindent 12 }}
            - name: LOGGING_LEVEL
              value: {{ .Values.worker.storage.profile.config.loggingLevel | quote }}
            - name: CONSUMER_TYPE
              value: "profile"
            - name: PULSAR_COLLECTOR_POOL
              value: "500"
{{ end }}