tracardi:
  dockerHubSecret: ""
  license: ""
  doSSL: "no"
  logging: "info"
  apiDocs: "no"
  trackDebug: "yes"
  saveLogsInTracardi: "yes"
  installationToken: "tracardi-install"
  image:
    webApi: tracardi/tracardi-api:0.8.0
    guiApi: tracardi/tracardi-api:0.8.0
    gui: tracardi/tracardi-gui:0.8.0
    worker: tracardi/worker:0.8.0
  replicas:
    webApi: 1
    guiApi: 1
    gui: 1
    worker: 1
  port:
    webApi: 8585
    guiApi: 8686
    gui: 8787
  workers:
    webApi: 5
    guiApi: 3
  destination:
    syncPostpone: 5
  pro:
    host: "pro.tracardi.com"
    port: "40000"
  scheduler:
    host: "scheduler.tracardi.com"
  elastic:
    host: elastic-cluster-es-http.elastic.svc.cluster.local
    schema: https
    username: elastic
    password: unset
    verifyCerts: "no"
    doCertId: "none"
  redis:
    host: redis://redis-master.redis.svc.cluster.local/0
    password: unset
    port: "6379"