{{ if and .Values.secrets.dockerHub .Values.bridge.queue.docker.enabled}}
#
# This is the deployment for commercial Queues Bridge
# This bridge includes:
#  * MQTT
#  * Kafka
#  * RabbitMQ
#  * IMAP
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bg-queue-prod
  labels:
    {{- include "tracardi.labels" (dict "ctx" . "component" "bg-queue-prod") | nindent 4 }}
spec:
  replicas: {{ .Values.bridge.queue.docker.replicas }}
  selector:
    matchLabels:
      {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "bg-queue-prod") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tracardi.podLabels" (dict "ctx" . "component" "bg-queue-prod") | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.secrets.dockerHub | quote }}
      containers:
      - name: bg-queue-prod
        image: "{{ .Values.bridge.queue.image.repository }}:{{ .Values.bridge.queue.image.tag }}"
        imagePullPolicy: {{ .Values.bridge.queue.image.pullPolicy }}
        resources:
          limits:
            memory: 100Mi
            cpu: 500m
          requests:
            memory: 80Mi
            cpu: 300m
        env:
          {{- include "tracardi.env" (dict "ctx" .) | nindent 10 }}
          - name: LOGGING_LEVEL
            value: {{ .Values.bridge.queue.docker.config.loggingLevel | quote }}
          - name: PRODUCTION
            value: "yes"
{{ end }}