{{ if and .Values.tracardi.dockerHubSecret .Values.tracardi.bridge.queue.license }}
#
# This is the deployment for commercial Queues Bridge
# This bridge includes:
#  * MQTT
#  * Kafka
#  * RabbitMQ
#  * IMAP
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: com-bridge-queue
  labels:
    tier: backend
spec:
  replicas: {{ .Values.tracardi.bridge.queue.replicas }}
  selector:
    matchLabels:
      app: com-bridge-queue
  template:
    metadata:
      labels:
        app: com-bridge-queue
        tier: backend
    spec:
      imagePullSecrets:
        - name: {{ .Values.tracardi.dockerHubSecret | quote }}
      containers:
      - name: com-bridge-queue
        image: {{ .Values.tracardi.bridge.queue.image }}
        imagePullPolicy: Always
        env:
          - name: ELASTIC_SCHEME
            value: {{ .Values.tracardi.elastic.schema | quote }}
          - name: ELASTIC_HOST
            value: {{ .Values.tracardi.elastic.host }}
          - name: ELASTIC_HTTP_AUTH_USERNAME
            value: {{ .Values.tracardi.elastic.username }}
          - name: ELASTIC_HTTP_AUTH_PASSWORD
            value: {{ .Values.tracardi.elastic.password }}
          - name: ELASTIC_PORT
            value: {{ .Values.tracardi.elastic.port | quote }}
          - name: ELASTIC_VERIFY_CERTS
            value: {{ .Values.tracardi.elastic.verifyCerts | quote }}
          - name: REDIS_HOST
            value: {{ .Values.tracardi.redis.host }}
          - name: REDIS_PASSWORD
            value: {{ .Values.tracardi.redis.password }}
          - name: POSTPONE_DESTINATION_SYNC
            value: {{ .Values.tracardi.worker.destination.syncPostpone | quote}}
          - name: ELASTIC_QUERY_TIMEOUT
            value: "120"
          - name: LOGGING_LEVEL
            value: {{ .Values.tracardi.worker.loggingLevel | quote }}
          - name: SOURCE_CACHE_TTL
            value: "60"
          - name: SESSION_CACHE_TTL
            value: "60"
          - name: EVENT_TAG_CACHE_TTL
            value: "60"
          - name: EVENT_VALIDATION_CACHE_TTL
            value: "60"
          - name: _DEBUG_VERSION
            value: "0.8.0"
          - name: LICENSE
            value: {{ .Values.tracardi.bridge.queue.license | quote }}
{{ end }}