apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-standalone-deployment
  labels:
    app: pulsar-standalone
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulsar-standalone
  template:
    metadata:
      labels:
        app: pulsar-standalone
        tier: backend
    spec:
      containers:
        - name: pulsar-standalone
          image: apachepulsar/pulsar:3.1.0
          command: ["bin/pulsar", "standalone"]
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 6Gi
              cpu: 1000m
            requests:
              memory: 512Mi
              cpu: 400m
          ports:
            - name: pulsar-port
              containerPort: 6650
            - name: http-port
              containerPort: 8080
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: pulsar-std-lb
#spec:
#  type: LoadBalancer
#  selector:
#    app: pulsar-standalone
#  ports:
#    - name: pulsar-port
#      protocol: TCP
#      port: 16655
#      targetPort: pulsar-port
#    - name: http-port
#      protocol: TCP
#      port: 18080
#      targetPort: http-port


---
apiVersion: v1
kind: Service
metadata:
  name: pulsar-std-svc
spec:
  type: ClusterIP
  selector:
    app: pulsar-standalone
  ports:
    - name: pulsar-port
      protocol: TCP
      port: 6650
      targetPort: pulsar-port
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: http-port