{{ if and .Values.secrets.dockerHub .Values.job.heartbeat.production.enabled }}
{{- $root := . -}}
{{- range $s := .Values.job.heartbeat.test.schedules }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $s.name }}
  labels:
    {{- include "tracardi.labels" (dict "ctx" $root "component" "jobs-group") | nindent 4 }}
spec:
  schedule: {{ $s.schedule | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 60
  successfulJobsHistoryLimit: {{ $root.Values.job.heartbeat.production.config.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ $root.Values.job.heartbeat.production.config.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: 2
      completions: 1
      parallelism: 1
      template:
        metadata:
          name: {{ $s.name }}
          labels:
            {{- include "tracardi.podLabels" (dict "ctx" $root "component" "jobs-group") | nindent 12 }}
        spec:
          imagePullSecrets:
            - name: {{ $root.Values.secrets.dockerHub | quote }}
          containers:
          - name: job-heartbeat-production
            image: "{{ $root.Values.job.heartbeat.image.repository }}:{{ $root.Values.job.heartbeat.image.tag }}"
            imagePullPolicy: "{{ $root.Values.job.heartbeat.image.pullPolicy }}"
            resources:
              limits:
                memory: 100Mi
                cpu: 500m
              requests:
                memory: 80Mi
                cpu: 300m
            env:
              {{- include "tracardi.env" (dict "ctx" $root) | nindent 14 }}
              - name: LOGGING_LEVEL
                value: {{ $root.Values.job.heartbeat.production.config.loggingLevel | quote }}
              - name: PRODUCTION
                value: "yes"
{{ if $s.range }}
              - name: RANGE
                value: {{ $s.range | quote }}
{{ end }}
{{ if $s.qualify_by }}
              - name: QUALIFY_BY
                value: {{ $s.qualify_by | quote }}
{{ end }}
{{ if $s.skip_seconds }}
              - name: SKIP_SECONDS
                value: {{ $s.skip_seconds | quote }}
{{ end }}
{{ if $s.no_events_within_last }}
              - name: NO_EVENTS_WITHIN_LAST
                value: {{ $s.no_events_within_last | quote }}
{{ end }}
{{ if $s.open_event_type }}
              - name: OPEN_EVENT_TYPE
                value: {{ $s.open_event_type | quote }}
{{ end }}
{{ if $s.close_event_type }}
              - name: CLOSE_EVENT_TYPE
                value: {{ $s.close_event_type | quote }}
{{ end }}
{{ if $s.ephemeral }}
              - name: EPHEMERAL
                value: {{ $s.ephemeral | quote }}
{{ end }}
          restartPolicy: OnFailure

---
{{- end }}
{{ end }}