apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tracardi-api.fullname" . }}-api-web-deployment
  labels:
    app: {{ include "tracardi-api.fullname" . }}-api-web
    tier: frontend
spec:
  replicas: {{ .Values.tracardi.system.replicas.webApi }}
  selector:
    matchLabels:
      app: {{ include "tracardi-api.fullname" . }}-api-web
  template:
    metadata:
      labels:
        app: {{ include "tracardi-api.fullname" . }}-api-web
        tier: backend
    spec:
{{ if .Values.tracardi.dockerHubSecret }}
      imagePullSecrets:
        - name: {{ .Values.tracardi.dockerHubSecret | quote }}
{{end}}
      containers:
        - name: {{ include "tracardi-api.fullname" . }}-api-web
          image: {{ .Values.tracardi.system.image.webApi }}
          imagePullPolicy: Always
          ports:
            - name: web-api-port
              containerPort: 80
          env:
            {{- include "tracardi.env" (dict "ctx" . "license" .Values.tracardi.system.license.secret) | nindent 12 }}
            - name: EXPOSE_GUI_API
              value: "no"
            - PRODUCTION:
              value: "yes"

---
apiVersion: v1
kind: Service
metadata:
  name: tracardi-api-web-svc
spec:
  type: ClusterIP
  selector:
    app: {{ include "tracardi-api.fullname" . }}-api-web
  ports:
    - protocol: TCP
      port: {{ .Values.tracardi.system.port.webApi }}
      targetPort: web-api-port

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: {{ include "tracardi-api.fullname" . }}-api-web-lb
#  annotations:
#    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
#    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
#    service.beta.kubernetes.io/do-loadbalancer-certificate-id: {{ .Values.elastic.doCertId | quote }}
#spec:
#  type: LoadBalancer
#  selector:
#    app: {{ include "tracardi-api.fullname" . }}-api-web
#  ports:
#    - name: http
#      protocol: TCP
#      port: {{ .Values.tracardi.system.port.webApi }}
#      targetPort: web-api-port
#    - name: https
#      protocol: TCP
#      port: 443
#      targetPort: web-api-port
