apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tracardi-api.fullname" . }}-api-gui-deployment
  labels:
    app: {{ include "tracardi-api.fullname" . }}-api-gui
    tier: backend
spec:
  replicas: {{ .Values.tracardi.system.replicas.guiApi }}
  selector:
    matchLabels:
      app: {{ include "tracardi-api.fullname" . }}-api-gui
  template:
    metadata:
      labels:
        app: {{ include "tracardi-api.fullname" . }}-api-gui
        tier: backend
    spec:
{{ if .Values.tracardi.dockerHubSecret }}
      imagePullSecrets:
        - name: {{ .Values.tracardi.dockerHubSecret | quote }}
{{end}}
      containers:
        - name: {{ include "tracardi-api.fullname" . }}-api-gui
          image: {{ .Values.tracardi.system.image.guiApi }}
          imagePullPolicy: Always
          ports:
            - name: gui-api-port
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 60
          env:
            {{- include "tracardi.env" (dict "ctx" . "license" .Values.tracardi.system.license.secret) | nindent 12 }}
            - name: EXPOSE_GUI_API
              value: "yes"
            - PRODUCTION:
              value: "no"

---
apiVersion: v1
kind: Service
metadata:
  name: tracardi-api-gui-svc
spec:
  type: ClusterIP
  selector:
    app: {{ include "tracardi-api.fullname" . }}-api-gui
  ports:
    - protocol: TCP
      port: {{ .Values.tracardi.system.port.guiApi }}
      targetPort: gui-api-port


#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: {{ include "tracardi-api.fullname" . }}-api-gui-lb
#  annotations:
#    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
#    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
#    service.beta.kubernetes.io/do-loadbalancer-certificate-id: {{ .Values.tracardi.doCertId | quote }}
#spec:
#  type: LoadBalancer
#  selector:
#    app: {{ include "tracardi-api.fullname" . }}-api-gui
#  ports:
#    - name: http
#      protocol: TCP
#      port: {{ .Values.tracardi.system.port.guiApi }}
#      targetPort: gui-api-port
#    - name: https
#      protocol: TCP
#      port: 443
#      targetPort: gui-api-port