{{ if and .Values.worker.flusher.profile.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wk-rd-flusher-profile
  labels:
    {{- include "tracardi.labels" (dict "ctx" . "component" "wk-rd-flusher-profile") | nindent 4 }}
spec:
  replicas: {{ .Values.worker.flusher.profile.replicas }}
  selector:
    matchLabels:
      {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "wk-rd-flusher-profile") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tracardi.podLabels" (dict "ctx" . "component" "wk-rd-flusher-profile") | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.secrets.dockerHub | quote }}
      containers:
        - name: wk-rd-flusher-profile
          image: "{{ .Values.worker.flusher.image.repository }}:{{ .Values.worker.flusher.image.tag }}"
          imagePullPolicy: {{ .Values.worker.flusher.image.pullPolicy }}
          resources:
            limits:
              memory: 50Mi
              cpu: 100m
            requests:
              memory: 35Mi
              cpu: 30m
          env:
            {{- include "tracardi.env" (dict "ctx" .) | nindent 12 }}
            - name: LOGGING_LEVEL
              value: {{ .Values.worker.flusher.profile.config.loggingLevel | quote }}
            - name: CONSUMER_TYPE
              value: "profile"
{{ end }}