---
apiVersion: v1
kind: Service
metadata:
  name: collector-lb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: api-collector
    app.kubernetes.io/instance: tracardi-com
    app.kubernetes.io/name: tracardi
  ports:
    - protocol: TCP
      port: {{ .Values.collector.port }}
      targetPort: coll-port

---
apiVersion: v1
kind: Service
metadata:
  name: staging-lb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: api-staging
    app.kubernetes.io/instance: tracardi-com
    app.kubernetes.io/name: tracardi
  ports:
    - protocol: TCP
      port: {{ .Values.staging.port }}
      targetPort: staging-port


---
apiVersion: v1
kind: Service
metadata:
  name: gui-lb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: gui
    app.kubernetes.io/instance: tracardi-com
    app.kubernetes.io/name: tracardi
  ports:
    - protocol: TCP
      port: {{ .Values.gui.port }}
      targetPort: gui-port