{{ if and .Values.secrets.dockerHub .Values.scheduler.license.existingSecret }}
#
# This is the deployment for scheduler. It is responsible for delayed events
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: com-scheduler
  labels:
    {{- include "tracardi.labels" (dict "ctx" . "component" "com-scheduler") | nindent 4 }}
spec:
  replicas: {{ .Values.scheduler.replicas }}
  selector:
    matchLabels:
      {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "com-scheduler") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tracardi.podLabels" (dict "ctx" . "component" "com-scheduler") | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.secrets.dockerHub | quote }}
      containers:
      - name: com-scheduler
        image: "{{ .Values.scheduler.image.repository }}:{{ .Values.scheduler.image.tag }}"
        imagePullPolicy: {{ .Values.scheduler.image.pullPolicy }}
        command: ["sh", "-c"]
        args: ["rqscheduler -i 1 --host {{ .Values.redis.host }} --port {{ .Values.redis.port }} --db 0 --password $REDIS_PASSWORD"]
        env:
          {{- include "tracardi.env" (dict "ctx" . "license" .Values.scheduler.license.existingSecret) | nindent 10 }}
          - name: LOGGING_LEVEL
            value: {{ .Values.scheduler.config.loggingLevel | quote }}

{{ end }}