apiVersion: v1
kind: Service
metadata:
  name: es-loadbalancer
  namespace: elastic
spec:
  type: LoadBalancer
  selector:
    app: elastic-cluster
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200