{{ if and .Values.tms.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms-deployment
  labels:
    {{- include "tracardi.labels" (dict "ctx" . "component" "tms") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "tms") | nindent 6 }}
  template:
    metadata:
      labels:
        app: tms
        {{- include "tracardi.podLabels" (dict "ctx" . "component" "tms") | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.secrets.dockerHub  | quote }}
      containers:
        - name: tms
          {{- include "tracardi.image" (dict "ctx" . "repo" .Values.config.image.tms.repository "tag" .Values.config.image.tag "policy" .Values.config.image.tms.pullPolicy) | nindent 10 }}
          ports:
            - containerPort: 80
              name: tms-port
          env:
            - name: LOGGING_LEVEL
              value: {{ .Values.tms.config.loggingLevel | quote }}
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: "tms"
                  key: "token-key"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: "tms"
                  key: "api-key"
---
apiVersion: v1
kind: Service
metadata:
  name: tms-svc
spec:
  type: ClusterIP
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "tms") | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ .Values.tms.port }}
      targetPort: tms-port

{{ if .Values.digitalOcean.loadBalancer }}
---
apiVersion: v1
kind: Service
metadata:
  name: do-tms-lb
  {{ if .Values.digitalOcean.certId }}
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: {{ .Values.digitalOcean.certId | quote }}
  {{ end }}
spec:
  type: LoadBalancer
  selector:
    app: tms
  ports:
    - name: http-{{ .Values.tms.port }}
      protocol: TCP
      port: {{ .Values.tms.port }}
      targetPort: tms-port
    {{ if .Values.digitalOcean.certId }}
    - name: https
      protocol: TCP
      port: 443
      targetPort: tms-port
    {{ end }}

{{ end }}
{{ end }}