apiVersion: v1
kind: Secret
metadata:
  name: elastic-secret
type: Opaque
stringData:
  key: "THE-KEY"

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
stringData:
  key: "THE-KEY"