{{ if and .Values.secrets.dockerHub .Values.staging.license.existingSecret }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gui-deployment
  labels:
    {{- include "tracardi.labels" (dict "ctx" . "component" "api-gui") | nindent 4 }}
spec:
  replicas: {{ .Values.staging.replicas }}
  selector:
    matchLabels:
      {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "api-gui") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tracardi.podLabels" (dict "ctx" . "component" "api-gui") | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.secrets.dockerHub  | quote }}
      containers:
        - name: api-gui
          image: "{{ .Values.staging.image.repository }}:{{ .Values.staging.image.tag }}"
          imagePullPolicy: {{ .Values.staging.image.pullPolicy }}
          ports:
            - name: api-gui-port
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 60
          env:
            {{- include "tracardi.env" (dict "ctx" . "license" .Values.staging.license.existingSecret) | nindent 12 }}
            - name: EXPOSE_GUI_API
              value: "yes"
            - name: LOGGING_LEVEL
              value: {{ .Values.staging.config.loggingLevel | quote }}
            - name: API_DOCS
              value: {{ .Values.staging.config.apiDocs | quote}}
            - name: SAVE_LOGS
              value: {{ .Values.staging.config.saveLogs | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-gui
spec:
  type: ClusterIP
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "api-gui") | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ .Values.staging.port }}
      targetPort: api-gui-port

{{ if .Values.digitalOcean.loadBalancer }}
---
apiVersion: v1
kind: Service
metadata:
  name: do-api-gui-lb
  {{ if .Values.digitalOcean.certId }}
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: {{ .Values.digitalOcean.certId | quote }}
  {{ end }}
spec:
  type: LoadBalancer
  selector:
    matchLabels:
      {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "api-gui") | nindent 6 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.staging.port }}
      targetPort: api-gui-port
    {{ if .Values.digitalOcean.certId }}
    - name: https
      protocol: TCP
      port: 443
      targetPort: api-gui-port
    {{ end }}

{{ end }}
{{ end }}


