{{ if .Values.production.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-web
  annotations:
      {{ toYaml .Values.production.ingress.annotations }}
spec:
  {{ if .Values.production.ingress.tls -}}
  tls:
  - secretName: {{ .Values.production.ingress.tls.secretName }}
  {{ end }}
  {{- with .Values.production.ingressClassName -}}
  ingressClassName: {{ . }}
  {{- end -}}
  rules:
  - host: {{ .Values.production.ingress.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-web
            port:
              number: {{ .Values.production.port }}
{{ end }}
---
{{ if .Values.staging.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gui
  annotations:
      {{ toYaml .Values.staging.ingress.annotations }}
spec:
  {{- if .Values.staging.ingress.tls }}
  tls:
  - secretName: {{ .Values.staging.ingress.tls.secretName }}
  {{ end }}
  {{- with .Values.staging.ingressClassName -}}
  ingressClassName: {{ . }}
  {{- end -}}
  rules:
  - host: {{ .Values.staging.ingress.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gui
            port:
              number: {{ .Values.staging.port }}
{{ end }}
---
{{ if .Values.gui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gui
  annotations:
      {{ toYaml .Values.gui.ingress.annotations }}
spec:
  {{ if .Values.gui.ingress.tls -}}
  tls:
  - secretName: {{ .Values.gui.ingress.tls.secretName }}
  {{ end }}
  {{- with .Values.gui.ingressClassName -}}
  ingressClassName: {{ . }}
  {{- end -}}
  rules:
  - host: {{ .Values.gui.ingress.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gui
            port:
              number: {{ .Values.gui.port }}
{{ end }}
---
{{ if .Values.bridge.rest.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bridge-rest
  annotations:
      {{ toYaml .Values.bridge.rest.ingress.annotations }}
spec:
  {{ if .Values.bridge.rest.ingress.tls -}}
  tls:
  - secretName: {{ .Values.bridge.rest.ingress.tls.secretName }}
  {{ end }}
  {{- with .Values.bridge.rest.ingressClassName -}}
  ingressClassName: {{ . }}
  {{- end -}}
  rules:
  - host: {{ .Values.bridge.rest.ingress.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bridge-rest
            port:
              number: 10000
{{ end }}
